name: Build and push

on:
  workflow_dispatch:
    inputs:
      TAG:
        required: true

env:
  TAG: ${{ github.event.inputs.TAG }}
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

jobs:
  loxilb:
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone
        uses: actions/checkout@v5
        with:
          repository: loxilb-io/loxilb
          ref: ${{ github.event.inputs.TAG }}
          fetch-depth: 0
          submodules: recursive
          path: loxilb
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./loxilb
          tags: "${{ vars.DOCKERHUB_USERNAME }}/loxilb:${{ github.event.inputs.TAG }}"
          build-args: |
            TAG=${{ github.event.inputs.TAG }}
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1

  loxilb-debug:
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone
        uses: actions/checkout@v5
        with:
          repository: loxilb-io/loxilb
          ref: ${{ github.event.inputs.TAG }}
          fetch-depth: 0
          submodules: recursive
          path: loxilb
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./loxilb
          tags: ${{ vars.DOCKERHUB_USERNAME }}/loxilb:${{ github.event.inputs.TAG }}-debug
          build-args: |
            TAG=${{ github.event.inputs.TAG }}
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
            EXTRA_CFLAGS="-DHAVE_DP_LOG_LVL_TRACE"

  kube-loxilb:
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone
        uses: actions/checkout@v5
        with:
          repository: loxilb-io/kube-loxilb
          ref: ${{ github.event.inputs.TAG }}
          fetch-depth: 0
          submodules: recursive
          path: kube-loxilb
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./kube-loxilb
          tags: "${{ vars.DOCKERHUB_USERNAME }}/kube-loxilb:${{ github.event.inputs.TAG }}"
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
